# Development overrides
services:
  frontend:
    build:
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "5173:5173"

  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - LOGGING_LEVEL_ROOT=DEBUG
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar app.jar

  dynamodb-local:
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

  valkey:
    ports:
      - "6379:6379"
    command: valkey-server --appendonly no